#ifndef GENERALALGORITHM_GLOBAL_H
#define GENERALALGORITHM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GENERALALGORITHM_LIBRARY)
#  define GENERALALGORITHMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GENERALALGORITHMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERALALGORITHM_GLOBAL_H
